# Generated by Django 3.2.8 on 2021-10-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('featured_image', models.ImageField(blank=True, upload_to='')),
                ('rank', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('embed', models.CharField(max_length=1000)),
            ],
        ),
    ]
