# Generated by Django 3.2.8 on 2021-10-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=240)),
                ('url', models.URLField()),
                ('repository_url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
